database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  dbname: im
  password: ANDWANG130.

redis:
  host: 127.0.0.1
  port: 6379
  password:
  max_active: 100
oss:
  Endpoint: http://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAIjduC3OLJCnEO
  accessKeySecret: Jkfcv3UJL1Y2TEeowiPABvV6MQi1cH
  bucketName: xkws
